version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./basic:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
    volumes:
      - ./basic:/var/www/html
